### ISSUE TITLE
how does Markdown accept spaces in an image url?

### ISSUE THREAD

**Issue by skinofthesoul** [xaprb/xaprb-src#2]
@xaprb I found [your blog post on how to style images with Markdown](https://www.xaprb.com/blog/how-to-style-images-with-markdown/) really helpful, thank you for that!

However, using the technique you showed with "classes" surrounded by spaces after a `#` in the image url, I found that my version of Markdown (I'm using [Grav](https://getgrav.org/)) needs to have the spaces encoded as `%20.` Apparently there are quite a few options here that may or may not work – [this thread on StackOverflow helped me out](https://stackoverflow.com/questions/34569256/link-to-filenames-with-spaces-in-bitbucket-markdown). Maybe this is an interesting bit of information to add to the article.

Anna~

Edit: Sorry for the title, I started writing before doing a proper internet search…! Can't seem to change that.

**Comment by xaprb** [comment]
Thank you Anna! Today I learned about Grav, which looks awesome. Thanks for that!
