### ISSUE TITLE
Where's the kittie?

### ISSUE THREAD

**Issue by influencerof** [xaprb/xaprb-src#3]
<img src="https://www.petmd.com/sites/default/files/petmd-kitten-development.jpg" alt="Kitten"
	title="A cute kitten" width="150" height="100" />
##

Great post, but it seems the kittie is missing

**Comment by xaprb** [comment]
Which post are you referring to?

**Comment by influencerof** [comment]
[Your Site's](https://www.xaprb.com/blog/how-to-style-images-with-markdown/) Great Writing

**Comment by tina1998612** [comment]
yeah the img in how-to-style-images-with-markdown.md is missing

**Comment by xaprb** [comment]
Maybe an adblock extension is causing a problem or something. It's not missing for me. https://www.xaprb.com/blog/how-to-style-images-with-markdown/
